qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/findbugs-exclude/LICENSE.txt
qulice-maven-plugin/src/it/findbugs-exclude/invoker.properties
qulice-maven-plugin/src/it/findbugs-exclude/pom.xml
qulice-maven-plugin/src/it/findbugs-exclude/src/main/java/com/qulice/foo/Bar.java
qulice-maven-plugin/src/it/findbugs-exclude/src/main/java/com/qulice/foo/Main.java
qulice-maven-plugin/src/it/findbugs-exclude/src/main/java/com/qulice/foo/package-info.java
qulice-maven-plugin/src/it/findbugs-exclude/verify.groovy
qulice-maven-plugin/src/site/apt/example-exclude.apt.vm

issue #352. Created integration test

#352 Created integration test

---

qulice-checkstyle/pom.xml
qulice-findbugs/pom.xml
qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java

This is a solution of puzzle #350

FindBugsValidatorTest.java:91-94: Add support for multiline excludes.... 

---

qulice-pmd/pom.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java

#454 
* PMD upgraded to 5.3.3
* added test to check handling of method references

#454 upgraded PMD to handle method references

---

README.md

#400
* added more explicit information about license file location

#400 added explanation for license

---

qulice-checkstyle/pom.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/DefaultMethods.java
qulice-maven-plugin/src/it/checkstyle-violations/src/main/java/com/qulice/plugin/violations/Violations.java
qulice-maven-plugin/src/it/checkstyle-violations/verify.groovy

#432
* added test that checks that the example provided in the issue actually works in the latest qulice

#432 added test to confirm default methods work

---

qulice-pmd/pom.xml

#462 upgraded to latest PMD

---

qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/hibernate-validator-check/LICENSE.txt
qulice-maven-plugin/src/it/hibernate-validator-check/invoker.properties
qulice-maven-plugin/src/it/hibernate-validator-check/pom.xml
qulice-maven-plugin/src/it/hibernate-validator-check/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/it/hibernate-validator-check/src/main/java/com/qulice/foo/package-info.java
qulice-maven-plugin/src/it/hibernate-validator-check/verify.groovy

#465
* recreated problem with IT test
* added hibernate validator as dependency

#465 added hibernate validators as dependency

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ConstantUsageCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ConstantUsageCheck/Valid.java

#420 
* recreated problem in test (`Valid.java`)
* fixed by checking inner class definition for private constants

#420 added handling of constants in inner classes

---

qulice-pmd/pom.xml
qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/FieldInitConstructor.java
qulice-pmd/src/test/resources/com/qulice/pmd/FieldInitNoConstructor.java

#470 
* created two test cases (with no constrcutor, and with one)
* implemented check using PMD xpath

#470 inline initialization of fields is forbidden

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ParametrizedClass.java

#472 
* added test to recreate the problem
* enabled JavadocType check to force documentation of class parameters

#472 enforce documentation of parameters

---

qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java
qulice-maven-plugin/src/it/findbugs-exclude/verify.groovy

#441 
* recreated problem in integration test
* fixed by moving created exclude files into temporary folder

#441 exclude files created in temp directory

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/BracketsStructureCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/BracketsStructureCheck/Valid.java

#489
* reproduce problem in unit test
* fix NPE by checking if list of expressions contains any element

#489 fix NPE in BracketsStructure check

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ConstantUsageCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AnnotationConstant.java

#447 
* recreated problem in unit test
* fixed handling of constants in method annotations
* added todo to fix problem in class and field annotations

#447 added handling of constants in annotations

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/StaticFieldInitConstructor.java

#491 
* recreated problem in unit test
* fixed PMD rule to ignore static fields

#491 fixed false error when during static field initialization

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AuthorTag.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/violations.txt

#412 
* recreated problem in unit test
* changed number of words required in the author name to 1

#412 added handling of nicks in author tag

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/LineWrapPackage.java

#520 Qulice does not enforce Checkstyle rule NoLineWrap
Added check rule in checks.xml
Added a source file to test and a test method in CheckstyleValidatorTest

#520 Qulice does not enforce Checkstyle rule NoLineWrap

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/CascadeIndentationCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/QuliceIndentationCheck.java
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InvalidIndentation.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidIndentation.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java

Resolving #556 Strict indentation check is wrong.
Added 2 unit tests.
Exception to the rule described in #556 : Lines in block comments

#556 Strict indentation check is wrong

---

est/001.est

For #485:
* project size estimated using Scope Champions method

#485 Estimate project size

---

qulice-ant/pom.xml
qulice-ant/src/main/java/com/qulice/ant/AntEnvironment.java
qulice-findbugs/pom.xml
qulice-gradle-plugin/pom.xml
qulice-maven-plugin/pom.xml

#370 
* removed findbugs (and fixed problems) exclude in qulice-ant, qulice-gradle-plugin, qulice-findbugs
* added todo to remove the exclude in qulice-maven-plugin

#370 removed findbugs exludes

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDAssert.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDDisabledRulesTest.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDEmptyTest.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/AvoidUsingVolatile.java
qulice-pmd/src/test/resources/com/qulice/pmd/DoNotUseThreads.java
qulice-pmd/src/test/resources/com/qulice/pmd/UseConcurrentHashMap.java

#569 
* slightly refactored pmd tests (extracted common class)
* added test to ensure that rules to be removed are really removed
* removed rules

#569 removed unnecesary rules

---

qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java

#590 
* removed findbugs exclude (except for one generated class) and updated code

#590 removed findbugs exclude

---

README.md
qulice-maven-plugin/src/site/fml/faq.fml

For #396:
* add summary from discussion in #393 to FAQ and README

#396 Add information about proxy usage to documentation

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ImportCohesionCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java

ArrayIndexOutOfBoundsException in ImportCohesionCheck on file with imports only #451

---

qulice-maven-plugin/pom.xml

#365
* enabled depdendency violations IT test and removed todo

#365 enabled IT test

---

qulice-maven-plugin/src/it/findbugs-violations/verify.groovy

#388 
* removed stale todo, it was fixed in #131

#388 removed stale todo

---

qulice-maven-plugin/src/main/java/com/qulice/maven/MojoExecutor.java

#351 
* releaseMojo is now in finally block

#351 moved relaseMojo

---

.rultor.yml

For #634:
* make changes in Rultor script before applying #637

#634 Modify Rultor script for #637

---

.rultor.yml
.travis.yml
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AnnotationConstant.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AtClauseOrder.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ConstructorParams.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/DefaultMethods.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ExtraSemicolon.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InstanceMethodRef.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InvalidIndentation.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/LineWrapPackage.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/LocalVariableNames.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ParametrizedClass.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ReturnCount.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/TooLongLines.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidIndentation.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidSemicolon.java

For #634:
* specify order of at-clauses (Oracle recommended order, then `@todo`, then `@checkstyle`
* add test

#634 Enforce at-clause order

---

.travis.yml

For #577:
* added new build to execute freshly built Qulice over entire code
* due to Travis YML syntax limitations two different commands must be
specified by environmental variables

#577 Perform dogfood check on Travis

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/CatchParameterNames.java

For #627 :
- regular expressions modified
- new test cases added

#627 naming of catch parameters

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/StringLiteralsConcatenationCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/StringLiteralsConcatenationCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/StringLiteralsConcatenationCheck/violations.txt

Fix for #502. 
Add recursive string literal search.

Fix StringLiteralsConcatenationCheck

---

qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/dependency-violations-exclude/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/it/dependency-violations/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/it/hibernate-validator-check/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/it/multi-module/mod-alpha/src/main/java/com/qulice/plugin/alpha/Main.java
qulice-maven-plugin/src/it/pmd-violations/src/main/java/com/qulice/foo/Violations.java
qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/JunitStaticPublicMethods.java
qulice-pmd/src/test/resources/com/qulice/pmd/StaticAccessToStaticFields.java
qulice-pmd/src/test/resources/com/qulice/pmd/StaticPublicMethod.java
qulice-pmd/src/test/resources/com/qulice/pmd/StaticPublicVoidMainMethod.java

For issue #659 
Added new rule to prohibit public static methods. 
~~Added puzzle to exclude rule StaticAccessToStaticFields.~~ Removed as not relevant.

#659 prohibit public static methods

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/DiamondOperatorCheck.java
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InvalidDiamondsUsage.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidDiamondsUsage.java

For #715 
Added new check usage of diamond operator.

#715: added use diamond operator check

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-maven-plugin/src/main/java/com/qulice/maven/CheckMojo.java
qulice-spi/src/main/java/com/qulice/spi/Violation.java

#741 
* added lines, check name and validator name to the Violations class
* fixed tests

#741 updated Violations

---

pom.xml
qulice-ant/src/main/java/com/qulice/ant/AntEnvironment.java
qulice-ant/src/main/java/com/qulice/ant/QuliceTask.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleListener.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/LineRanges.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/StringLiteralsConcatenationCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-codenarc/src/test/java/com/qulice/codenarc/CodeNarcValidatorTest.java
qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java
qulice-findbugs/src/main/java/com/qulice/findbugs/Wrap.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/AbstractQuliceMojo.java
qulice-maven-plugin/src/main/java/com/qulice/maven/CheckMojo.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DependenciesValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DuplicateFinderValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/EnforcerValidator.java
qulice-maven-plugin/src/test/java/com/qulice/maven/DependenciesValidatorTest.java
qulice-maven-plugin/src/test/java/com/qulice/maven/MavenEnvironmentMocker.java
qulice-maven-plugin/src/test/java/com/qulice/maven/ValidatorsProviderMocker.java
qulice-pmd/src/main/java/com/qulice/pmd/Files.java
qulice-pmd/src/main/java/com/qulice/pmd/PmdListener.java
qulice-pmd/src/main/java/com/qulice/pmd/SourceValidator.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-spi/src/main/java/com/qulice/spi/Environment.java
qulice-xml/src/main/java/com/qulice/xml/Prettifier.java

Qulice should use source level 1.7 #725

#725 Qulice should use source level 1.7

---

qulice-checkstyle/pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/BracketsStructureCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/ConstantUsageCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CurlyBracketsStructureCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/DiamondOperatorCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/EmptyLinesCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/FinalSemicolonInTryWithResourcesCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocEmptyLineCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocLocationCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/MethodBodyCommentsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/MethodsOrderCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/MultilineJavadocTagsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/NoJavadocForOverriddenMethodsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/NonStaticMethodCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProtectedMethodInFinalClassCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/StringLiteralsConcatenationCheck.java

#856 Checkstyle minor upgrade to improve performance

#856 Checkstyle minor upgrade to improve performance

---

qulice-ant/pom.xml
qulice-maven-plugin/pom.xml

For #821 removing dependency on qulice-xml and qulice-codenarc (which were removed).

#821 removing dependency on removed modules

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidLiteralComparisonCheck.java

#807.
Removed check, and added test.

#807 Remove EqualsAvoidNull check from Qulice 

---

qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/DiamondUsageNotNeeded.java

#850 Added testcase for not requiring diamond usage in case of return statement

#850 adding test for diamond usage

---

.0pdd.yml
.pdd
.rultor.yml

#889 
Moved pdd exclusions to .pdd, added errors email to myself just in case, simplified rultor config (because of better `.pdd` file)

#889 trying to fix 0pdd/pdd

---

qulice-checkstyle/pom.xml

#889 dummy pdd to test if 0pdd works

#889 dummy pdd

---

qulice-pmd/src/main/java/com/qulice/pmd/rules/UseStringIsEmptyRule.java
qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/UseStringIsEmptyRuleTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/LocalStringLength.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringFromMethodLength.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthEqualsZero.java

PR for #801 
Added the specified PMD rule and unit tests for it. 
Also, added todo puzzle to enhance the rule and also catch the `this.` case.

UseStringIsEmptyRule and unit tests

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/FilesCreateFileOther.java
qulice-pmd/src/test/resources/com/qulice/pmd/FilesCreateFileTest.java

#877 
- created test for testing that `Files.createFile` is forbidden in test classes

#877 test for forbiding Files.createFile in tests

---

qulice-findbugs/pom.xml
qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java

#906 Get rid of xembly as a dependency

---

qulice-maven-plugin/src/it/pmd-violations/invoker.properties
qulice-maven-plugin/src/it/pmd-violations/pom.xml
qulice-maven-plugin/src/it/pmd-violations/src/main/util/some.tex
qulice-maven-plugin/src/it/pmd-violations/verify.groovy
qulice-maven-plugin/src/main/java/com/qulice/maven/CheckMojo.java
qulice-maven-plugin/src/test/java/com/qulice/maven/CheckMojoTest.java
qulice-pmd/pom.xml
qulice-pmd/src/main/java/com/qulice/pmd/SourceValidator.java

#909 
Added logging of currently processed file in PMD.

#909 logging file being processed

---

README.md
qulice-maven-plugin/src/site/apt/usage.apt.vm

#794 
* added minimal maven version to usage and README usage

#794 added min maven version

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProtectedMethodInFinalClassCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ProtectedMethodInFinalClassCheck/Valid.java

#901 
* protected methods are now allowed if they are inherited (and have `@Override` annotation)
* updated test

#901 allow protected methods if they have override annotation

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/CatchParameterNames.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InstanceMethodRef.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/LocalVariableNames.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidSemicolon.java

#576 
* added empty lines separator check, so each member of a class is separated by a single line

#576 empty lines check added

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml

#908 
* removed PMD rule AvoidInstantiatingObjectsInLoops

#908 removed AvoidInstantiatingObjectsInLoops

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml

Excluding CommentDefaultAccessModifier from PMD

Excluding CommentDefaultAccessModifier from PMD

---

qulice-checkstyle/pom.xml
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/DoNotUseCharEncoding.java

For #784:
What was made:
- added check for `Charsets`
- added tests for `Charsets`

For #784: Usages of Charsets should be discouraged in favor of StandardCharsets

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml

#951 
* correcting suppression filters path to use classpath

#951 fixing suppresions

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/EmptyLinesCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/EmptyLinesCheck/Valid.java

#953 
* handling multiple inner anonymous methods
* added test to validate behavior

#953 correcting emptylines check for anonymous methods

---

qulice-checkstyle/pom.xml
qulice-pmd/pom.xml

#961 
- upgraded to newest checkstyle and PMD

#961 upgraded checkstyle and pmd

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdDisabledRulesTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/DefaultPackage.java
qulice-pmd/src/test/resources/com/qulice/pmd/ExcessiveImports.java

#963 
- removed DefaultPackage and ExcessiveImports PMD checks
- added tests to verify that

#963 removed PMD rules

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/TooLongLines.java

#867 
* set line length to 100 chars

#867 line legth set to 100 chars

---

.rultor.yml

#950 
* fix for deprecated gem options

#950 fix rultor

---

.travis.yml

#950 
* fixing also travis config

#950 fixing also travis

---

qulice-pmd/src/main/java/com/qulice/pmd/rules/UseStringIsEmptyRule.java
qulice-pmd/src/test/java/com/qulice/pmd/UseStringIsEmptyRuleTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthEqualsZeroMethod.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthEqualsZeroThis.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthGreaterOrEqualOneMethod.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthGreaterOrEqualOneThis.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthLessThanOneMethod.java
qulice-pmd/src/test/resources/com/qulice/pmd/StringLengthLessThanOneThis.java

For #950:
- Added tests for `UseStringIsEmptyRule` when the tested string is accessed using `this.` or by a method
- Left puzzle for fixing the implementation
- Left puzzle for completing the tests with all the conditions

For #950: Tests for UseStringIsEmptyRule

---

qulice-checkstyle/pom.xml

#949 remove stale todo

---

.rultor.yml
.travis.yml

#966 
* disable xcop for now (so we can upgrade it later)

#966 temporarly disable xcop

---

qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ConstantUsageCheck/Valid.java

For #921: 
Looks like the problem does not happens anymore, made a test to prove this

For #921: Proof that ConstantUsageCheck false positive does not happen

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProtectedMethodInFinalClassCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ProtectedMethodInFinalClassCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ProtectedMethodInFinalClassCheck/violations.txt

For #1006: 
- Making `ProtectedMethodInFinalClassCheck` stricter by adding checks.
- Corrected tests for new check.

For #1006: Making ProtectedMethodInFinalClassCheck stricter.

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProhibitNonFinalClassesCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ProhibitNonFinalClassesCheck/config.xml

For #1007: Forbid non final classes.
- Implemented `ProhibitNonFinalClassesCheck.java` check
- Added check to test and production environments (`ChecksTest` and `config.xml`)
- Removed puzzle

For #1007: Forbid non final classes.

---

pom.xml
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/MissingJavadocTest.java
qulice-findbugs/src/test/java/com/qulice/findbugs/FindBugsValidatorTest.java
qulice-maven-plugin/pom.xml
qulice-pmd/src/test/resources/com/qulice/pmd/AllowAssertFail.java
qulice-pmd/src/test/resources/com/qulice/pmd/ExcessiveImports.java
qulice-pmd/src/test/resources/com/qulice/pmd/PlainJUnitAssertionStaticImportBlock.java
qulice-pmd/src/test/resources/com/qulice/pmd/PlainJUnitAssertionTestMethod.java

For #1019: 
- Upgraded all projects except `maven-qulice-plugin` to Junit5.
- Left puzzle in `maven-qulice-plugin` to upgrade it to Junit5.

For #1019: Upgraded all projects except maven-qulice-plugin to Junit5.

---

qulice-pmd/src/main/java/com/qulice/pmd/rules/UseStringIsEmptyRule.java
qulice-pmd/src/test/java/com/qulice/pmd/UseStringIsEmptyRuleTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/ArrayOfStringsLengthGreaterThanZero.java

For #1031
- Add test case where used String[].length.
- Fix UseStringIsEmptyRule, now it does not detect this case.

#1031. Now UseStringIsEmptyRule not detect String[].length > 0.

---

images/button-m.svg
images/button-s.svg

For #913: README.md badge draft.

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/EmptyCollectionRuleTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/NullCollection.java

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
I went through the above checklist and I can say "yes" to each point. This code change includes a test case and an additional rule (Return empty collection rather than null) for fixing issue 793.

Fix issue 793

---

.github/workflows/reports-check.yml

This action will validate quality of incoming bug reports (github issues here) and post the possible improvements to the author of that report. Example of work: 
More information you can find in our [README](https://github.com/tracehubpm/reports-check-action)

reports-check.yml

---

pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/ConstantUsageCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/ImportCohesionCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocParameterOrderCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/MultilineJavadocTagsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/NonStaticMethodCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProhibitNonFinalClassesCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/QualifyInnerClassCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/parameters/Arguments.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/parameters/TypeParameters.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/duplicate-finder-violations/verify.groovy
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DependenciesValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DuplicateFinderValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/MojoExecutor.java
qulice-maven-plugin/src/main/java/com/qulice/maven/SnapshotsValidator.java
qulice-maven-plugin/src/test/java/com/qulice/maven/DefaultMavenEnvironmentTest.java
qulice-maven-plugin/src/test/java/com/qulice/maven/DefaultValidatorsProviderTest.java
qulice-maven-plugin/src/test/java/com/qulice/maven/PomXpathValidatorTest.java
qulice-pmd/src/main/java/com/qulice/pmd/PmdListener.java
qulice-pmd/src/main/java/com/qulice/pmd/SourceValidator.java
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-spi/src/main/java/com/qulice/spi/Violation.java
qulice-spi/src/test/java/com/qulice/spi/EnvironmentTest.java

- fix new warnings.
- changed parameter for duplicate-finder-plugin ignoredResources (was deleted) to ignoredResourcePatterns

Update qulice to 0.22.2

---

qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/SwaggerApi.java

#1129 Add test with swagger annotation

---

qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/duplicate-finder-ignore-deps/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/DuplicateFinderValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/MojoExecutor.java
qulice-maven-plugin/src/site/apt/example-exclude.apt.vm

Add exclusions for dulicatefinder plugin for classes and packages
Fix #1118

#1118 Add exclusions for duplicatefinder

---

pom.xml
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/EnforcerValidator.java

Update some dependencies
instead of #1233 #1228 #1177

Update guava and maven-enforcer-plugin

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml

id is needed for the rule to be able to disable it
Fix #976

#976 Add id for Checkstyle Regexp* rules

---

qulice-spi/src/main/java/com/qulice/spi/Environment.java

@yegor256 
This Pull request solves this problem: #1343

Environment.Mock.files() Hardcoded to "src" Directory (Limited Testability)

---

pom.xml
qulice-checkstyle/pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/RequiredJavaDocTag.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/AbstractQuliceMojo.java
qulice-pmd/pom.xml
qulice-spi/pom.xml

#1363: Update dependencies

---

.rultor.yml

@yegor256 Remove maven colors and put in batch mode when using rultor.

#1378: Remove maven colors and put in batch mode when using rultor
