pom.xml
qulice-maven-plugin/src/it/codenarc-violations/module/LICENSE.txt
qulice-maven-plugin/src/it/codenarc-violations/module/pom.xml
qulice-maven-plugin/src/it/js-violations/LICENSE.txt
qulice-maven-plugin/src/it/js-violations/pom.xml

Issue #366 resolved.
qulice-maven-plugin:0.12 removed from pom.xml
parent updated to 0.32

#366  qulice-maven-plugin:0.12 removed from pom.xml, parent updated to 0.32

---

qulice-checkstyle/pom.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/RedundantThrowsCheckTest.java

Introduced a test.
Should pass on qulice 0.10+ (requires checkstyle 5.7+), fails on qulice 0.3.1.
Qulice master branch uses checkstyle 5.7, therefore it is good to go.

#113 - RedundantThrowsCheck for inner classes - introduced test

---

qulice-maven-plugin/src/it/checkstyle-violations/src/main/java/com/qulice/plugin/violations/IndentationChecks.java
qulice-maven-plugin/src/it/checkstyle-violations/verify.groovy

The `IndentationCheck` bug described was fixed in Checkstyle 5.9. See http://checkstyle.sourceforge.net/releasenotes.html and https://github.com/checkstyle/checkstyle/issues/294. I added a test case to show that it is working now.

#139 Verify that IndentationCheck bug is not present

---

qulice-maven-plugin/src/main/java/com/qulice/maven/PomXpathValidator.java

**Before**
Check pom.xml with XPath validation queries. Restrictions: 1. Each xpath component should contains namespace prefix pom: 2. Each xpath query should end with /text()
**After**
> Check pom.xml with XPath validation queries.
> 
> Restrictions:
>
> 1. Each xpath component should contains namespace prefix pom:
> 2. Each xpath query should end with /text()
Updated pull request #433 according to input from @krzyk

 Fix PomXpathValidator javadoc

---

qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/relocation/LICENSE.txt
qulice-maven-plugin/src/it/relocation/invoker.properties
qulice-maven-plugin/src/it/relocation/pom.xml
qulice-maven-plugin/src/it/relocation/verify.groovy
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java

#448
* recreated problem in integration test (using a dependency that has the `<relocation>` in pom)
* `<relocation>` tag was causing NPE (this dependency doesn't have a jar) - fixed by checking if artifact has a file associated

#448 fixed NPE problem in Maven Env

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ConstructorParams.java

#471 
* added test to check the new condition for constructor params (allow same name as fields) and for method params (no change)
* fixed by adding `HiddenField` parameter

#471 tuned check to not report a problem when constructor params equal  fields

---

qulice-maven-plugin/src/it/xml-violations/src/site.xml
qulice-xml/src/main/java/com/qulice/xml/Prettifier.java
qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java
qulice-xml/src/test/java/com/qulice/xml/XmlValidatorTest.java

#469 
* fixed problem with XML preambule (now it is required, including encoding)
* fixed problem with comment before the first XML tag
* fixed problem with new line at the and of XML (it is required now)
* added todo to fix incorrect attribute formatting

#469 fixed xml formatting problems

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ReturnCount.java

* ReturnCount check is configured to enforce at most one return statement in each method
* Integration test is added
Implementation for #515.

#515 Disallow methods with multiple return statements

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/checkstyle-locale/LICENSE.txt
qulice-maven-plugin/src/it/checkstyle-locale/invoker.properties
qulice-maven-plugin/src/it/checkstyle-locale/pom.xml
qulice-maven-plugin/src/it/checkstyle-locale/src/main/resources/tabs.txt
qulice-maven-plugin/src/it/checkstyle-locale/verify.groovy

* Checkstyle is configured to use only English language in error messages
* New integration test is created to make sure that Qulice always uses English messages, even if environment locale is different
Implementation for #519.

#519 Fix build for non-English locale

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/StrictIndentation.java

For #527:
* change config for Indentation check to enforce strict indentation (not more spaces than needed)
* unit test added

#527 Enable strict condition in Checkstyle Indentation check

---

qulice-checkstyle/pom.xml

Additional fix for #519:
* There is integration test to verify completion of issue #519 introduced in #529
* `ChecksTest` was randomly failing when it was run on JVM with non-English locale, this commit fixes it
* There's no other possibility to verify whether tests work correctly except running another build, but this idea was rejected in https://github.com/teamed/qulice/pull/529#discussion_r48008636
* All difficulty with locale here is connected to the fact, that Checkstyle statically caches all error messages and uses localized ones by default
* Any test can populate static cache with localized messages and then next test has dirty state and messages in different message than expected

#519 Fix integration test for non-English locale

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/FinalSemicolonInTryWithResourcesCheck.java
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ExtraSemicolon.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidSemicolon.java

Resolving #461 Prohibit a semicolon in the end of try-with-resourses head.
Checkstyle consider final (optional) semicolon as belonging to the RESOURCE_SPECIFICATION token, so it is enough to test if RESOURCE_SPECIFICATION contains a semicolon.

#461 Prohibit a semicolon in the end of try-with-resourses head

---

pom.xml
qulice-ant/pom.xml
qulice-ant/src/test/java/com/qulice/ant/AntEnvironmentTest.java
qulice-checkstyle/pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleListener.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/StringLiteralsConcatenationCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/LicenseRule.java
qulice-findbugs/pom.xml
qulice-findbugs/src/main/java/com/qulice/findbugs/Wrap.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/AbstractQuliceMojo.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DuplicateFinderValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/MavenEnvironment.java
qulice-maven-plugin/src/test/java/com/qulice/maven/MavenEnvironmentMocker.java
qulice-pmd/src/main/java/com/qulice/pmd/PmdListener.java
qulice-pmd/src/main/java/com/qulice/pmd/SourceValidator.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-spi/src/main/java/com/qulice/spi/Environment.java
qulice-xml/pom.xml
qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java

Resolving #553 
* upgrade dependencies
* enforce jcabi-aspects version for qulice-xml (see issues jcabi/jcabi-aspects#194 and jcabi/jcabi-xml#73)
* qulice 0.14 compliance
* force flushing writer in PMD tests before match

Upgrade dependencies #553

---

qulice-maven-plugin/src/it/findbugs-exclude/pom.xml
qulice-maven-plugin/src/site/apt/example-exclude.apt.vm

For #421:
* Add two separate exclusions instead of one in integration test (we have two files with violations already, test is failing when leaving just one of them)
* Remove puzzle from the code
* Adjust documentation

#421 Add test for multiline exclusion for FindBugs

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/violations.txt

For #495:
* Instead of validating only first Javadoc tag, all of them are gathered to the `List` and then validated
* Test is added to confirm the behaviour

#495 Validate all author tags in JavadocTags check

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/LocalVariableNames.java

For #376:
* Limit local variables and catch parameters to 12 chars
* Remove `ex` from `LocalVariableName`, as this check from Checkstyle 6.14 doesn't validate catch parameters anymore
* Disable catch parameters validation in `LocalFinalVariableName` by setting property `tokens` to `VARIABLE_DEF`
* Add `CatchParameterName` introduced in Checkstyle 6.14 with pattern same as it was previously used for local variables
* Add test with input file

#376 Modify rules for local variable names

---

.rultor.yml
.travis.yml

For #581:
* Rultor config (based on various examples from search https://github.com/search?utf8=%E2%9C%93&q=gem+install+est+filename%3A.rultor.yml&type=Code&ref=searchresults):
* install est
* make install faster for pdd by skipping docs
* add estimates check
* add missing newline at the end of file 
* Travis config
* install pdd and est with `set -e` (based on https://github.com/jcabi/jcabi-dynamo/blob/6ab5f80beb9b3016cbd818cf6c3ef77c6ddddee0/.travis.yml and https://github.com/yegor256/s3auth/blob/a2f7cc35e407d9d43051351100baabf1ee42e312/.travis.yml)
* invoke pdd and est

#581 Configure pdd and est in Travis and Rultor

---

pom.xml
qulice-xml/pom.xml
qulice-xml/src/test/java/com/qulice/xml/XmlValidatorTest.java

Unit test for #498.
XmlValidator should properly fail XML files without schema with `ValidationException`. And it does inside `qulice-xml` module that uses `jcabi-xml` version **0.15**. `qulice-maven-plugin` on the other hand uses  `jcabi-xml` version **0.17** and fails the same test with vague `NullPoinerException`.
Easily reproducible by updating `jcabi-xml` version inside `qulice-xml/pom.xml` to **0.17**.
Probably caused by https://github.com/jcabi/jcabi-xml/issues/94.

XmlValidator should properly fail XML files without schema

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/TooLongLines.java

For #592:
* enable line length check for Javadoc tags by removing it from ignored pattern
* provide test to verify that too long comments are not ignored

#592 Enable LineLength check for Javadoc tags

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/NonStaticMethodCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/violations.txt

For #595:
* Added sample with method with `@Override` that should not cause violation despite not referencing `this`
* Added sample with method with other annotation that cause violation
* Provided additional documentation
* Implementation was pretty straightforward - just one more condition added

#595 Ignore '@Override' methods in NonStaticMethod check

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java

Fixed typo in CheckstyleValidator

---

pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-pmd/src/main/java/com/qulice/pmd/rules/UnnecessaryLocalRule.java
qulice-pmd/src/test/java/com/qulice/pmd/PMDDisabledRulesTest.java
qulice-spi/src/main/java/com/qulice/spi/Environment.java

For #609:
* update Qulice to 0.15.2
* replace usages of `ConcurrentHashMap` with `HashMap`
* remove suppression
* remove puzzle

#609 Remove unnecessary usages of 'ConcurrentHashMap'

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/NonStaticMethodCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/violations.txt
qulice-spi/src/main/java/com/qulice/spi/Environment.java

For #603:
* excluded native and abstract methods from the check
* provided positive and negative test case
* removed obsolete suppression related to `@Override`

#603 Ignore abstract and native methods in NonStaticMethod check

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/MethodBodyCommentsCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/MethodBodyCommentsCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/MethodBodyCommentsCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/MethodBodyCommentsCheck/violations.txt

For #371:
* add one condition to implementation
* extend tests with various cases

#371 Prohibit multi-line comments in MethodBodyComments check

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/NonStaticAccessToStaticFields.java
qulice-pmd/src/test/resources/com/qulice/pmd/StaticAccessToStaticFields.java

Resolving #611 by PMD XPath rule.
Added A positive and a negative unit test.

#611 Static constants are not checked to have class specified

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/LocalVariableNames.java

Solving issue #593
How I solved it
allowing 'id' or 3 to 12 characters at final, non final local variables and member names.
allowing 'id' or at leat 3 characters at method parameters names
refactoring test to match new restrictions.
ignoring 'FinalLocalVariable' check when testing the variables names (we don't need to test it here)

Allowing variables with minimum 2 characters

---

pom.xml
qulice-ant/pom.xml
qulice-checkstyle/pom.xml
qulice-codenarc/pom.xml
qulice-findbugs/pom.xml
qulice-gradle-plugin/pom.xml
qulice-maven-plugin/pom.xml
qulice-pmd/pom.xml
qulice-spi/pom.xml
qulice-xml/pom.xml

Resolving #578. Replace configuration in submodules only.
Pages for qulice should stay at root.

#578 fix Page 'qulice.com' is currently broken

---

qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/dependency-violations-exclude/LICENSE.txt
qulice-maven-plugin/src/it/dependency-violations-exclude/invoker.properties
qulice-maven-plugin/src/it/dependency-violations-exclude/pom.xml
qulice-maven-plugin/src/it/dependency-violations-exclude/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/it/dependency-violations-exclude/src/main/java/com/qulice/foo/package-info.java
qulice-maven-plugin/src/it/dependency-violations-exclude/verify.groovy
qulice-maven-plugin/src/main/java/com/qulice/maven/DependenciesValidator.java
qulice-maven-plugin/src/site/apt/example-exclude.apt.vm
qulice-maven-plugin/src/test/java/com/qulice/maven/DependenciesValidatorTest.java

#398 
* added exclude support for dependency validation (using `dependencies:groupId:artifactId`)
* excluding all dependencies will now need `dependencies:.*`

#398 added exludes for dependencies

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/UrlInLongLine.java

Simply added a new regex pattern to the "ignorePattern" property in checkstyles lineLength module.
Ticket for this PR: #625

Checkstyles ignores long lines if they have a URL #625

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/NonStaticMethodCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Valid.java

#623 Methods that throw exceptions are valid non-static methods. Updated the check and verified it with a change to the test.

#623 Methods that throw exceptions are valid non-static methods

---

qulice-findbugs/pom.xml
qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java
qulice-findbugs/src/main/java/com/qulice/findbugs/Wrap.java
qulice-findbugs/src/test/java/com/qulice/findbugs/FindBugsValidatorTest.java

#144 
* using fb-contrib rule `BED_BOGUS_EXCEPTION_DECLARATION` to check for throws declaration with reality
* one drawback is that this check ignores public methods - this is sometimes required for APIs (see mebigfatguy/fb-contrib#92), but the good news is that it works for final methods/classes so it should cover almost all classes (as qulice enforces them to be final if they are not abstract)

#144 throws should be real

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/config.xml
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidIT.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidITCase.java
qulice-spi/src/main/java/com/qulice/spi/Environment.java
years.sh

For #666:
* Extend pattern for `NonStaticMethodCheck`
* Add tests
* Remove suppressions
* Remove obsolete branch in bash

#666 Disable static method check for ITs and small fixes

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/NonStaticMethodCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/NonStaticMethodCheck/violations.txt

#623 Updated code and tests to find methods that should static if they catch and re-throw an exception.

Invalidate methods that throw from a catch that could otherwise be static

---

qulice-checkstyle/pom.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AnnotationIndentation.java

For #411:
* Update Checkstyle to 6.15
* Add test confirming that indentation works correctly now

#411 Allow proper indentation in complex annotations

---

qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java
qulice-maven-plugin/src/test/java/com/qulice/maven/DefaultMavenEnvironmentTest.java

For issue #676 
Problem was in `DefaultMavenEnvironment.exludes` when Collection [null, null, null] returned if exclusion don't match checker 'dependecies'
Fixed problem, added not null filter for method DefaultMavenEnvironment.exludes, so now empty collection turns back if no matchings

#676 npe dependency validator

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/DoNotUseCharEncoding.java

For #655:
* Use regexp rule to prohibit usages of `CharEncoding`
* Add test case

#655 Prohibit usages of 'CharEncoding'

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PMDValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/AllowNonTransientFields.java

For issue #675 
Added test to check if class can contain non-static non-transient field. Test failed.
Fixed test - excluded rule `BeanMembersShouldSerialize ` from ruleset.

#675: excluded non-static non-transient pmd rule

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InvalidAbbreviationAsWordInNameXML.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidAbbreviationAsWordInName.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidAbbreviationAsWordInNameIT.java

#660 AbbreviationAsWordInNameCheck configured:
* Set allowed abbreviation size to 1 so to not allow those
* Set "IT" as the only exception as allowed uppercase abbreviation
* Static final fields as well as overrides are not checked by default and needed no config
Added tests for:
* Abbreviations XML/HTML are detected as standard violations
* IT is not a violation
* Static final fields are not checked
* Correctly named classes pass the check
* Overrides are not checked

#660 implemented AbbreviationsAsWordInNameCheck

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/AllowsDuplicateLiteralsInAnnotations.java

#760 PMD's AvoidDuplicateLiterals is not equivalent to original MultipleStringLiteralsCheck
I have changed skipAnnotations property to true, which allows AvoidDuplicateLiterals to skip check for Annotations

#760 PMD's AvoidDuplicateLiterals is not equivalent to original MultipleStringLiteralsCheck

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml

#863 Abstract naming rules don't match well with new `Envelops` so removing those rules.

#863 getting rid of abstract naming rules

---

pom.xml
qulice-maven-plugin/src/it/pmd-violations/pom.xml
qulice-maven-plugin/src/it/pmd-violations/src/main/java/com/qulice/foo/Violations.java

#925 
commons-lang3 version we were using from jcabi-parent was incompatible with the one from PMD, added correct version to deps, and added a test to guard that change.

#925 fix error with commons-lang3

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/suppressions.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/MissingJavadocTest.java
qulice-maven-plugin/src/it/checkstyle-violations/verify.groovy

#848
* removed requirement for method javadocs in test classes

#848 dont require javadoc for methods in tests

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-pmd/src/test/java/com/qulice/pmd/LocalVariableCouldBeFinalRuleTest.java
qulice-pmd/src/test/java/com/qulice/pmd/UnusedImportsRuleTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/LocalVariableCouldBeFinal.java
qulice-pmd/src/test/resources/com/qulice/pmd/UnusedImports.java

For #772: Removal of overlapping checks of PMD and checkstyle´
- Added tests for `UnusedImports` and `LocalVariableCouldBeFinal` PMD checks]
- Removed those checks from `checkstyle`
- Left puzzle for continuing implementation

For #772: Removal of overlapping checks of PMD and checkstyle

---

pom.xml
qulice-spotbugs/LICENSE.txt
qulice-spotbugs/pom.xml
qulice-spotbugs/src/main/java/com/qulice/spotbugs/SpotBugsValidator.java
qulice-spotbugs/src/main/java/com/qulice/spotbugs/package-info.java
qulice-spotbugs/src/test/java/com.qulice.spotbugs/SpotBugsValidatorTest.java
qulice-spotbugs/src/test/java/com.qulice.spotbugs/package-info.java

For #884:
- Added dependencies and `SpotBugsValidation` skeleton `SpotBug` checks
- Added `SpotBugsValidationTests` which tests basic `SpotBugsValidator` behavior
- Added puzzle for resuming implementation

For #884: Replace FindBugs with SpotBugs

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdDisabledRulesTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/PositionLiteralsFirstInComparisons.java

#963
* PMD added another rule that we will remove for now: PositionLiteralsFirstInComparisons and PositionLiteralsFirstInCaseInsensitiveComparisons

#963 removed another rule

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdDisabledRulesTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/MissingSerialVersionUID.java

#963 
* disabled requirement for serialVersionUID (not many projects need serializable, but many extend from Exceptions)

#963 remove requirement for serial version UID

---

qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/LambdaInConstructor.java

For #887: Ignore lambdas on constructors.
- Created test assuring that `PMD` is ignoring lambda in constructors

For #887: Ignore lambdas on constructors.

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocParameterOrderCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/config.xml
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/violations.txt

For #847: Enforce parameter order in javadoc
- Added test for parameter order check
- Left puzzle to complete check implementation

For #847: Enforce parameter order in javadoc

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocTagsCheck/violations.txt

For #743: Nested classes should have since tag
- Changed `JavadocTagsCheck` tests so it does not pass when `since` tag is absent in nested class
- Removed `JavadocTagsCheck` test execution; the test fails now
- Added puzzle for `JavadocTagsCheck` correction and re-activation of tests

For #743: Nested classes should have since tag

---

qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidLambdaAndGenericsAtEndOfLine.java

For #897:
- Added test for `RegexpSingleline` to accept `>` as last line character when in lambda arrows or generics
- Added todo for implementing the correct behavior and removing ignore from test

For #897: Test for RegexpSingleline behavior change

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProtectedMethodInFinalClassCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ProtectedMethodInFinalClassCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/ProtectedMethodInFinalClassCheck/violations.txt

For #917:
- Added condition to failure test: when a default method is overrided by a protected one in a final class checkstyle should complain
- Added puzzle for completion of the task

For #917: Make ProtectedMethodInFinalClassCheck stricter.

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/QualifyInnerClassCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/QualifyInnerClassCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/QualifyInnerClassCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/QualifyInnerClassCheck/config.xml
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/QualifyInnerClassCheck/violations.txt

For #738: Qulaify inner classes
- Addes test to ensure that inner classes are being accessed through qualified name
- Left puzzle for check implementatio

For #738: Qulaify inner classes

---

pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/LicenseRule.java
qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java
qulice-findbugs/src/mock/java/com/qulice/findbugs/BytecodeMocker.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/PomXpathValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/SvnPropertiesValidator.java
qulice-maven-plugin/src/test/java/com/qulice/maven/CheckMojoTest.java
qulice-maven-plugin/src/test/java/com/qulice/maven/PomXpathValidatorTest.java
qulice-pmd/src/test/java/com/qulice/pmd/PmdAssert.java
qulice-spi/src/main/java/com/qulice/spi/Environment.java

This update brought several problems, which failed the build.
They have all been resolved in this commit.
Release 0.48.5 brought a change to commons-collections,
this has been altered in the pom.xml.
Several IO methods have been deprecated. They implicitly
used `Charset.defaultCharset()`, so to keep it functionally
the same as before this change, I've made these usages
explicitly.
`StandardCharsets.UTF_8` is now the standard for JDK8+.
`Mockito.anyCollectionOf(File.class)` has been deprecated,
because since JDK8 `Mockito.anyCollection()` already deals
correctly with casting.

For #966 Update jcabi parent to 0.49.3

---

.rultor.yml

#913 
* master is broken because it wasn't cleaned after the last release, added `mvn clean` before merge action

#913-2 fixing master

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidLambdaAndGenericsAtEndOfLine.java

For #1005:
- Changed regex in `checks.xml` allowing `->` and `<*>` at end of lines
- Removed `@Ignore` from test and todo
- Fixed sample class name

For #1005: Allow -> and <> at end of lines

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocParameterOrderCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/violations.txt

Fix IndexOutOfBoundsException occurs when number of @param tags is less then number of actual parameters.
See #1034

For #1034: Fix IndexOutOfBoundsException in JavadocParameterOrderCheck

---

pom.xml
qulice-checkstyle/pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProhibitNonFinalClassesCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/LicenseRule.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/main/java/com/qulice/maven/SvnPropertiesValidator.java
qulice-pmd/pom.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdAssert.java

For #1009 
- Delete commons-io dependency from pom.xml
- Add Cactoos 0.41 to qulice-pmd
- Replace `IOUtils` on `TextOf`
And
- Upgrade Cactoos to 0.41

#1009. Replace Commons-io on Cactoos in qulice-pmd.

---

pom.xml
qulice-checkstyle/pom.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java

For #1037 
- Upgrade [ChecksTest](https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java) from Junit4 to Junit5.
- Now [ChecksTest](https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java) from qulice-pmd runs automatically when building by maven.

For #1037:Upgrade ChecksTest from qulice-checkstyle to Junit5.

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocParameterOrderCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/parameters/Arguments.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/parameters/Parameters.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/parameters/TypeParameters.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/parameters/package-info.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/JavadocParameterOrderCheck/violations.txt

For #1046 
- Add test cases
- Implemented functionality for working with Generic parameters

For #1046. Now JavadocParameterOrderCheck works with Generic parameters.

---

src/site/site.xml

Replace broken src link to [working one](https://camo.githubusercontent.com/21b0e8be23deb3c2743027b82fda3af26c04ebfbb43faf5fc73c01b66607f8bf/687474703a2f2f696d672e71756c6963652e636f6d2f6c6f676f2e737667) from readme.md

Fix the logo on qulice.com

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml

#1055 
https://checkstyle.sourceforge.io/config_regexp.html#RegexpSingleline

#1055: RegexpSinglelineCheck applies to *.png, *.js, *.css files

---

qulice-pmd/src/main/java/com/qulice/pmd/PmdValidator.java

PMD check is performed also for files (folders) specified in the exclusion list, which takes time. 
This commit excludes such files.

Excluding files from PMD checking

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/test/java/com/qulice/maven/ValidationExclusionTest.java
qulice-maven-plugin/src/test/resources/com/qulice/maven/ValidationExclusion/CheckstyleExample.txt
qulice-maven-plugin/src/test/resources/com/qulice/maven/ValidationExclusion/PmdExample.txt
qulice-pmd/src/main/java/com/qulice/pmd/PmdValidator.java

Checkstyle validation is performed also for files (folders) specified in the exclusion lists in POM. Only violations are filtered out in PMD and Checkstyle validators.
Excessive processing consumes a lot of time.
This commit excludes specified files from validation.
Also tests for the current changes and changes in  #1103  were added.

Excluding files from Checkstyle validation

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml

I enabled ignoreOverriddenMethods for ParameterNumberCheck. As this option is already unit tested in checkstyle https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java#L99, I think no unit test is needed in qulice. But I built a snapshot of qulice and ran mvn qulice:check in one of my own java projects. Violation is now only tagged at the place where the method is defined originally, but not where it is being overridden.

#1062, ignore overridden methods for parameter number check

---

qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-maven-plugin/src/it/checkstyle-violations/src/main/java/com/qulice/plugin/violations/Юникод.java

This PR is for reproducing this issue: https://github.com/objectionary/eo-hamcrest/issues/87
Note that this is only half of the problem and may help reproduce the issue with parsing Unicode characters in class names.

added integration test with unicode characters

---

qulice-maven-plugin/src/it/multi-module/mod-alpha/src/test/java/com/qulice/plugin/alpha/MainTest.java
qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/AllowAssertFail.java
qulice-pmd/src/test/resources/com/qulice/pmd/JunitStaticPublicMethods.java
qulice-pmd/src/test/resources/com/qulice/pmd/TestShouldBePackagePrivate.java

Closes: #1130
Related to: https://github.com/objectionary/eo/issues/1035
According to:  https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#junit5testshouldbepackageprivate
Reports JUnit 5 test classes and methods that are not package-private. Contrary to JUnit 4 tests, which required public visibility to be run by the engine, JUnit 5 tests can also be run if they’re package-private. Marking them as such is a good practice to limit their visibility.
Test methods are identified as those which use `@Test`, `@RepeatedTest`, `@TestFactory`, `@TestTemplate` or `@ParameterizedTest`.

added JUnit5TestShouldBePackagePrivate to qulice pmd ruleset

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/AllowAssertFail.java
qulice-pmd/src/test/resources/com/qulice/pmd/Junit3TestClassShouldBeFinal.java
qulice-pmd/src/test/resources/com/qulice/pmd/Junit4TestClassShouldBeFinal.java
qulice-pmd/src/test/resources/com/qulice/pmd/Junit5TestClassShouldBeFinal.java
qulice-pmd/src/test/resources/com/qulice/pmd/JunitStaticPublicMethods.java
qulice-pmd/src/test/resources/com/qulice/pmd/JunitTestClassIsFinal.java

Closes: #1158 
What is done:
- added a new rule to the PMD ruleset to report on test classes declared non-final;
- added support for JUnit3, JUnit4 and JUnit5 test classes;
- Wrote some tests.

reports on JUnit test classes declared non-final.

---

qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AnnotationIndentationNegative.java

AFAIU this todo was created 7 years ago. Checkstyle dependency was updated since than, and it looks like now improperly formatted code is properly rejected.
Closes #1128

Remove outdated todo

---

qulice-pmd/pom.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdEmptyTest.java

From what I see, TODO from #1116 is no longer relevant: I removed `parallel`, and tests still pass.

Run qulice-pmd tests in parallel

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/SingleLineCommentCheck.java
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidSingleLineCommentCheck.java

Previously it was implemented using a regex. However this approach is inherently not accurate, leading to problems like iss. 1079.
This patch converts to it AST-based check pass which should have no false-positives.

Improve single-line block comment check

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/BranchContains.java

Closes: #1180 
branchContains method was deprecated in checkstyle due to unexpected side-effects (too deep subtree scanning) and it's recommended to write your own traversal implementations for per need. BranchContains class is quite universal implementation for most needs, so i think it shouldn't be removed.
although, BranchContains class is only used in NonStaticMethodCheck for now and it's possible to move the BranchContains functionality to NonStaticMethodCheck's private method (we can discuss which way is better)

justification for BranchContains usage

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/AccessToStaticFieldsViaThis.java
qulice-pmd/src/test/resources/com/qulice/pmd/AccessToStaticMethodsViaThis.java
qulice-pmd/src/test/resources/com/qulice/pmd/DirectAccessToStaticFields.java

Add pmd-xpath rule that prohibits access to static fields/methods via instance reference (particularly 'this' keyword).
Closes: #984

Prohibit access to static members via instance reference.

---

qulice-ant/src/main/java/com/qulice/ant/AntEnvironment.java
qulice-ant/src/main/java/com/qulice/ant/AntPath.java
qulice-ant/src/main/java/com/qulice/ant/AntProject.java
qulice-ant/src/main/java/com/qulice/ant/QuliceTask.java
qulice-ant/src/test/java/com/qulice/ant/AntEnvironmentTest.java

This PR adds a simple test for one of AntEnvironment methods.
This class currently directly uses some Ant class which complicates testing. This PR replaces them with interfaces which allow simple fake implementations.

Add simple buildsClassloader test

---

qulice-pmd/src/main/java/com/qulice/pmd/PmdError.java
qulice-pmd/src/main/java/com/qulice/pmd/PmdListener.java
qulice-pmd/src/main/java/com/qulice/pmd/PmdRenderer.java
qulice-pmd/src/main/java/com/qulice/pmd/PmdValidator.java
qulice-pmd/src/main/java/com/qulice/pmd/SourceValidator.java
qulice-pmd/src/test/java/com/qulice/pmd/PmdAssert.java
qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java

When PMD observes a processing error, such as parsing error, it stores it into a `Report` instance. However, this is not instance which is later used by qulice-pmd, so the error is lost.
This PR attaches a `Renderer` which remembers there new reports and later pushes them to listener.
Relevant PMD code references:
- https://github.com/pmd/pmd/blob/pmd_releases/6.10.0/pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java#L108
- https://github.com/pmd/pmd/blob/pmd_releases/6.10.0/pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java#L54
P.S. It is possible that issue can be alternatively solved with some other `Report` management strategy.

Report PMD processing errors

---

qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
qulice-pmd/src/test/resources/com/qulice/pmd/UnderstandsMethodReferences.java

Closes: #1193
Related to that issue puzzle states `todo #1129 Replace not+empty() with more precise containsInAnyOrder`. 
Although, the initial purpose of the test (checking that there's no `UnusedPrivateMethod` violation) was lost due to a typo in code sample (https://github.com/yegor256/qulice/commit/81fd2573431eaab4994496efb1726196048aee14).
So I refactored the test a little bit:
- implemented the check `not+containsString("(UnusedPrivateMethod)")` instead of `containsInAnyOrder`, it seems clearer to me
- put the sample code to a separate file and used PmdAssert class for validation

Refactor PmdValidatorTest#understandsMethodReferences test

---

qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml
qulice-pmd/src/test/resources/com/qulice/pmd/StaticAccessToStaticFields.java

- rule AvoidAccessToStaticMembersViaThis fixed to get only current class methods and fields
- remove deprecation warnings
Fix #1197

[#1197] fix AvoidAccessToStaticMembersViaThis rule

---

.github/workflows/reports-check.yml

@pnatashap take a look, please
In [prev](https://github.com/yegor256/qulice/pull/1232) Pr I forgot add permissions needed to run the check. Without them workflow will be failed with a message:
```
"Error: Resource not accessible by integration"
```
Here I added them:
* `issues` write
* `contents` read

issue permissions to reports-check.yml

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/DiamondOperatorCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidDiamondsUsage.java
qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml

- disable PMD.UseDiamondOperator
- one more exception for DiamondOperatorCheck
Fix #1242

[#1242] fix diamond operator false positive warning

---

qulice-pmd/src/main/java/com/qulice/pmd/rules/ProhibitPlainJunitAssertionsRule.java
qulice-pmd/src/main/java/com/qulice/pmd/rules/UnnecessaryLocalRule.java

Part of migrating to PMD7
From migration guide:
"When reporting a violation, you might see a deprecation of the addViolation methods. These methods have been moved to RuleContext. E.g. instead of addViolation(data, node, ...) use asCtx(data).addViolation(node, ...)."

Fix deprecated addViolation usage

---

pom.xml
qulice-checkstyle/pom.xml
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CascadeIndentationCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/CheckstyleValidator.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-maven-plugin/pom.xml
qulice-maven-plugin/src/it/dependency-violations-exclude/pom.xml
qulice-maven-plugin/src/it/dependency-violations-exclude/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/it/dependency-violations/src/main/java/com/qulice/foo/Sample.java
qulice-maven-plugin/src/main/java/com/qulice/maven/CheckMojo.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java
qulice-maven-plugin/src/main/java/com/qulice/maven/DependenciesValidator.java
qulice-maven-plugin/src/main/java/com/qulice/maven/MojoExecutor.java
qulice-pmd/pom.xml
qulice-spi/src/main/java/com/qulice/spi/Environment.java

Update to commons-io 2.16.0
Instead of #1153 #1209

Update commons-io to 2.16

---

qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java

These tests are currently disabled, but in fact one already passes and another almost-passes.
Additionally reported violations are now checked used hamcrest. AFAIU this resolves #1127

Verify reported violations in HeaderCheck tests

---

.github/workflows/mvn.yml

Java 21 has long-term vendor support, unlike Java 20

Use Java 21 in CI

---

qulice-spi/src/main/java/com/qulice/spi/Violation.java

Default threshold is [10 methods](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#toomanymethods), and `Violation` interface has only 5, so there is no need to suppress anything

Do not suppress warnings in Violation

---

qulice-maven-plugin/src/main/java/com/qulice/maven/CheckMojo.java

@pnatashap @yegor256 
Please review.
The flag 'threadSafe = true' has been added to the CheckMojo class. This should fix [1024](https://github.com/yegor256/qulice/issues/1024)

Added flag 'threadSafe = true' to CheckMojo class

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/MultiLineCommentCheck.java
qulice-checkstyle/src/main/java/com/qulice/checkstyle/RequiredJavaDocTag.java
qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml
qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/RequiredJavaDocTagTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/CommentCheck/Invalid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/CommentCheck/Valid.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/CommentCheck/config.xml
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ChecksTest/CommentCheck/violations.txt
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidLiteralComparisonCheck.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/ValidSingleLineCommentCheck.java

@pnatashap @yegor256 
Please review, this should resolve the issue [1079](https://github.com/yegor256/qulice/issues/1079).

1. Fixed a bug when adding extra spaces after the parameter name. 2. Fixed a bug when using comment-like text in string literals.

---

qulice-checkstyle/src/main/java/com/qulice/checkstyle/MultilineJavadocTagsCheck.java
qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
qulice-checkstyle/src/test/resources/com/qulice/checkstyle/InvalidMethodDoc.java

This change fixes the issue #1318. Now MultilineJavadocTagsCheck doesn't throw an unhandled exception if it meets a block comment instead of a javadoc comment.

Fix MultilineJavadocTagsCheck failing on block comments

---

.github/workflows/mvn.yml

@yegor256 Add ubuntu-22.04, macos-14 and windows-2025 to CI build. Can you check it out?

#1373: Add ubuntu-22.04, macos-14 and windows-2025 to CI build
